### ISSUE TITLE
make local fails

### ISSUE THREAD

**Issue by robomotic** [contentauth/c2pa-python-example#26]
I followed the README.
I run make local:
```

--- Building containers........ 

docker compose build
[+] Building 0.0s (0/1)                                                                                                                          docker:default
[+] Building 0/1
[+] Building 52.8s (8/14)                                                                                                                        docker:default 
 => [setup internal] load build context                                                                                                                    0.1s
 => => transferring context: 614.99kB                                                                                                                      0.0s
 => [setup build 2/5] WORKDIR /usr/src/app                                                                                                                 0.2s 
 => [setup build 3/5] COPY requirements.txt ./                                                                                                             0.1s 
 => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                                                                  10.1s
 => => #   Downloading Flask_Cors-5.0.0-py2.py3-none-any.whl.metadata (5.5 kB)                                                                                 
[+] Building 52.9s (8/14)                                                                                                                   docker:default     
 => [setup internal] load build context                                                                                                               0.1s     
 => => transferring context: 614.99kB                                                                                                                 0.0s      
 => [setup build 2/5] WORKDIR /usr/src/app                                                                                                            0.2s     
 => [setup build 3/5] COPY requirements.txt ./                                                                                                        0.1s5
 => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                                                             10.3s53.0s 
[+] Building 53.0s (8/14)                                                                                                    docker:default 
 => [setup internal] load build context                                                                                                0.1s
 => => transferring context: 614.99kB                                                                                                  0.0s 
 => [setup build 2/5] WORKDIR /usr/src/app                                                                                             0.2s
 => [setup build 3/5] COPY requirements.txt ./                                                                                         0.1s 
 => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                                              10.4s
 => => #   Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)                                                        [+] Building 53.1s (8/14)                                                                                        docker:default
 => [setup internal] load build context                                                                                    0.1s 
 => => transferring context: 614.99kB                                                                                      0.0s
 => [setup build 2/5] WORKDIR /usr/src/app                                                                                 0.2s 
 => [setup build 3/5] COPY requirements.txt ./                                                                             0.1s
 => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                                  10.5s 
 => => #   Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)                                                          
[+] Building 53.3s (8/14)                                              docker:default                                           
 => [setup internal] load build context                                          0.1s                                          
 => => transferring context: 614.99kB                                            0.0s(line 8))                                  
 => [setup build 2/5] WORKDIR /usr/src/app                                       0.2s                                           
 => [setup build 3/5] COPY requirements.txt ./                                   0.1s 
 => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt        10.6s  53.3s 
 => => # Collecting asn1crypto (from python-pkcs11->-r requirements.txt (line 9[+] Building 53.5s (8/14)       [+] Build[+ => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                            38.7s
[+] Building 122.5s (15/16)                                                                                docker:default
[+] Building 123.2s (23/24)                                                                                docker:default
[+] Building 123.7s (32/32) FINISHED                                                                       docker:default
 => [setup internal] load build definition from Dockerfile                                                           0.1s
 => => transferring dockerfile: 734B                                                                                 0.0s 
 => [client internal] load metadata for docker.io/library/python:3.12                                                2.0s
 => [setup auth] library/python:pull token for registry-1.docker.io                                                  0.0s
 => [setup internal] load .dockerignore                                                                              0.1s
 => => transferring context: 181B                                                                                    0.0s
 => [client build 1/5] FROM docker.io/library/python:3.12@sha256:251ef8e69b6ccdf3c7bf7effaa51179d59af35364dd9c8646  40.8s
 => => resolve docker.io/library/python:3.12@sha256:251ef8e69b6ccdf3c7bf7effaa51179d59af35364dd9c86469142aa72a2c8cf  0.0s 
 => => sha256:0a96bdb8280554b560ffee0f2e5f9843dc7b625f28192021ee103ecbcc2d629b 48.50MB / 48.50MB                     8.7s 
 => => sha256:54c7be425079efba0003054ee884bf72f1ffebca733bedd6f077d2809ee9aa6f 23.87MB / 23.87MB                     7.6s 
 => => sha256:7aa8176e6d893aff4b57b2c22574ec2afadff4673b8e0954e275244bfd3d7bc1 64.39MB / 64.39MB                    23.5s 
 => => sha256:251ef8e69b6ccdf3c7bf7effaa51179d59af35364dd9c86469142aa72a2c8cfc 9.72kB / 9.72kB                       0.0s
 => => sha256:fd304df3579ddb2df079c560619d7fdba78ffb56bad7d61aa0a6e36ee1a2d0db 2.32kB / 2.32kB                       0.0s
 => => sha256:acda8b87a53fdba562e5dd1d52f64b95fa96f2c1eb92df388e53f3ccc07c921b 6.06kB / 6.06kB                       0.0s
 => => sha256:1523f4b3f5602bf41caf8d8e649536ac0b3e56984c81a9f518fb20c6516ca075 211.31MB / 211.31MB                  36.3s
 => => sha256:e3696bf6d1aef6794bb24eb2058c7a46b4deece447f2b77b1d3556db98fa14e7 6.16MB / 6.16MB                      10.1s
 => => extracting sha256:0a96bdb8280554b560ffee0f2e5f9843dc7b625f28192021ee103ecbcc2d629b                            0.9s
 => => extracting sha256:54c7be425079efba0003054ee884bf72f1ffebca733bedd6f077d2809ee9aa6f                            0.3s
 => => sha256:9668c23f1ccbf2e8456efa32652be75ceeaa20c9ecbc079dce2fc1e97bd3ec5d 25.61MB / 25.61MB                    15.5s
 => => sha256:cc9fb0d581e78e017831733b79ce3d1769324556079721865ea80db1363405ba 248B / 248B                          15.6s
 => => extracting sha256:7aa8176e6d893aff4b57b2c22574ec2afadff4673b8e0954e275244bfd3d7bc1                            1.2s
 => => extracting sha256:1523f4b3f5602bf41caf8d8e649536ac0b3e56984c81a9f518fb20c6516ca075                            3.2s
 => => extracting sha256:e3696bf6d1aef6794bb24eb2058c7a46b4deece447f2b77b1d3556db98fa14e7                            0.2s
 => => extracting sha256:9668c23f1ccbf2e8456efa32652be75ceeaa20c9ecbc079dce2fc1e97bd3ec5d                            0.4s
 => => extracting sha256:cc9fb0d581e78e017831733b79ce3d1769324556079721865ea80db1363405ba                            0.0s
 => [setup internal] load build context                                                                              0.1s
 => => transferring context: 614.99kB                                                                                0.0s
 => CACHED [client build 2/5] WORKDIR /usr/src/app                                                                   0.2s
 => [setup build 3/5] COPY requirements.txt ./                                                                       0.1s
 => [setup build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                            38.7s
 => [setup build 5/5] COPY . .                                                                                       0.1s
 => [setup local-setup 1/4] RUN apt-get update     && apt-get install -y     less     jq                             4.4s
 => [setup local-setup 2/4] RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"   9.1s
 => [setup local-setup 3/4] RUN python3 -m pip install --upgrade localstack                                         19.6s
 => [setup local-setup 4/4] RUN pip install awscli-local[ver2]                                                       6.0s
 => [setup] exporting to image                                                                                       1.8s
 => => exporting layers                                                                                              1.8s
 => => writing image sha256:ceaf8b8a44ec25346e128aa03b8a15f2f5003b17591fabf538653bf4120acc1f                         0.0s
 => => naming to docker.io/library/local-setup:latest                                                                0.0s
 => [setup] resolving provenance for metadata file                                                                   0.0s
 => [signer internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 734B                                                                                 0.0s
 => [signer internal] load .dockerignore                                                                             0.0s
 => => transferring context: 181B                                                                                    0.0s
 => [signer internal] load build context                                                                             0.0s
 => => transferring context: 3.07kB                                                                                  0.0s
 => CACHED [signer build 3/5] COPY requirements.txt ./                                                               0.0s
 => CACHED [signer build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                     0.0s
 => CACHED [signer build 5/5] COPY . .                                                                               0.0s
 => [signer] exporting to image                                                                                      0.1s
 => => exporting layers                                                                                              0.0s
 => => writing image sha256:ea7c51811ea217870167e5706a7a58c578152f7480b92b3009852ad463f67137                         0.0s
 => => naming to docker.io/library/local-signer:latest                                                               0.0s
 => [signer] resolving provenance for metadata file                                                                  0.0s
 => [client internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 734B                                                                                 0.0s
 => [client internal] load .dockerignore                                                                             0.0s
 => => transferring context: 181B                                                                                    0.0s
 => [client internal] load build context                                                                             0.0s
 => => transferring context: 2.52kB                                                                                  0.0s
 => CACHED [client build 3/5] COPY requirements.txt ./                                                               0.0s
 => CACHED [client build 4/5] RUN pip install --no-cache-dir -r requirements.txt                                     0.0s
 => CACHED [client build 5/5] COPY . .                                                                               0.0s
 => [client] exporting to image                                                                                      0.0s
[+] Building 3/3 layers                                                                                              0.0s
 ✔ Service setup   Built                                                                                           122.6s 
 ✔ Service signer  Built                                                                                             0.7s 
 ✔ Service client  Built                                                                                             0.5s 

--- Running containers......... 

docker compose up -d
[+] Running 24/1
 ✔ localstack Pulled                                                                                                66.0s 
[+] Running 6/6
 ✔ Network c2pa-python-example_default      Created                                                                  0.1s 
 ✔ Volume "c2pa-python-example_local-data"  Created                                                                  0.0s 
 ✔ Container local-setup                    Exited                                                                   5.6s 
 ✔ Container localstack-main                Started                                                                  1.0s 
 ✘ Container local-signer                   Error                                                                    6.2s 
 ✔ Container local-client                   Created                                                                  0.1s 
dependency failed to start: container local-signer exited (1)
make: *** [Makefile:9: run] Error 1
```

Everything seems but the local-signer produced an error so I investigated and found this:
```
 *  Executing task: docker logs --tail 1000 -f a13e8f51baca491638d78928a860becf0fa490398f833eee6b1c626edcc09674 

Using KMS for signing
Traceback (most recent call last):
  File "/usr/src/app/app.py", line 78, in <module>
    kms_key_id = app_config['KMS_KEY_ID']
                 ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'KMS_KEY_ID'
 *  Terminal will be reused by tasks, press any key to close it. 

```
I am a bit confused, I understood the "make local" command creates a virtual local AWS environment thus not needing any real KMS keys?
Please let me know if I am mistaken.
Cheers.

**Comment by robomotic** [comment]
I found the issue to be in the local-setup,sh which is run inside the Dockerfile:
```

Starting setup
Creating a test user in localstack
Traceback (most recent call last):
  File "/usr/local/bin/awslocal", line 87, in main
    import awscli.clidriver  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'awscli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/awslocal", line 268, in <module>
    main()
  File "/usr/local/bin/awslocal", line 89, in main
    return run_as_separate_process()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/awslocal", line 158, in run_as_separate_process
    run(cmd_args, env_dict)
  File "/usr/local/bin/awslocal", line 68, in run
    os.execvpe(cmd[0], cmd, env)
  File "<frozen os>", line 618, in execvpe
  File "<frozen os>", line 650, in _execvpe
  File "<frozen os>", line 642, in _execvpe
OSError: [Errno 8] Exec format error: b'/usr/local/bin/aws'
Creating test credentials in localstack and saving them to .env.local file
Traceback (most recent call last):
  File "/usr/local/bin/awslocal", line 87, in main
    import awscli.clidriver  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'awscli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/awslocal", line 268, in <module>
    main()
  File "/usr/local/bin/awslocal", line 89, in main
    return run_as_separate_process()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/awslocal", line 158, in run_as_separate_process
    run(cmd_args, env_dict)
  File "/usr/local/bin/awslocal", line 68, in run
    os.execvpe(cmd[0], cmd, env)
  File "<frozen os>", line 618, in execvpe
  File "<frozen os>", line 650, in _execvpe
  File "<frozen os>", line 642, in _execvpe
OSError: [Errno 8] Exec format error: b'/usr/local/bin/aws'
Creating KMS key in localstack
Using default environment to build environment and KMS client
No env file path received as param. Looking at other possible locations...
Loading environment variables from .env.local file defined in env vars
Running example setup in dev mode with endpoint: http://localstack:4566
Traceback (most recent call last):
  File "/usr/src/app/setup.py", line 255, in <module>
    arguably.run()
  File "/usr/local/lib/python3.12/site-packages/arguably/_context.py", line 732, in run
    result = cmd.call(parsed_args)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/arguably/_commands.py", line 409, in call
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/setup.py", line 148, in create_key_and_csr
    key_id = create_kms_key(env_file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/setup.py", line 94, in create_kms_key
    kms = read_env_params()
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/app/setup.py", line 63, in read_env_params
    aws_access_key_id = app_config['AWS_ACCESS_KEY_ID']
                        ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'AWS_ACCESS_KEY_ID'
Creating root CA certificate
..+......+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+...+......+.......+..+...+...+.+...+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.....+...+......+.+...............+.......................+.+..+....+.....+...+.............+.....+.......+.....+...+............+.......+...........+............+......+.......+..+...............+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..........+......+.+.....+...+.+..............+......+.+......+........+.+...+...+...+..+...+...................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.....+.+..+.........+....+......+......+.....+............+.+.....+......+.+.....+...+......+..........+..................+.....+.+......+.....+......+...+.......+.................+.......+........+.......+.....+......+...+....+...+...+..+.........+...+.......+.....+...+.+..+..........+..+.+......+...+...........+..........+.....+.+.....+...+...+...+....+...............+.....+.+.........+..+...+......+....+...+...+.....+....+..+...............+.........+....+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
Signing the csr with the local cert
Can't open "kms-signing.csr" for reading, No such file or directory
40C7841DB27F0000:error:80000002:system library:BIO_new_file:No such file or directory:../crypto/bio/bss_file.c:67:calling fopen(kms-signing.csr, r)
40C7841DB27F0000:error:10000080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:75:
Unable to load certificate request input
Copying kms-signing.crt to local_volume/kms-signing.crt
cat: kms-signing.crt: No such file or directory
Copying chain.pem to local_volume/chain.pem
Adding CERT_CHAIN_PATH to .env.local
Adding CLIENT ENV_VARS to .env.local
Adding APP ENV_VARS to .env.local
Copying .env.local to local_volume/.env
cp: cannot stat 'kms-signing.crt': No such file or directory
```
So it seems awscli was not included in the dependences inside the image.
I am going to try to fix that and see if I can progress.

**Comment by robomotic** [comment]
I can confirm including that in the pip worked.

**Comment by Fayking24** [comment]
hello, I have the same trouble, could you please help me and send the fixed version of the code? Big thanks

**Comment by davejp** [comment]
> hello, I have the same trouble, could you please help me and send the fixed version of the code? Big thanks

For an immediate fix, try adding `awscli` to `requirements.txt` — the command should succeed after that.
