### ISSUE TITLE
COSE error parsing certificate

### ISSUE THREAD

**Issue by shayan-NECX** [contentauth/c2pa-python-example#9]
Thanks a lot for sharing the tutorial. I followed it thoroughly, created KMS key, CSR and certificates and chain pem file. But when i run flask app and send a curl request of an image, it gives the following error. On cURL request end, it doesn't give any error and downloads an empty file. I created certificate via openssl.

Please let me know if you have any pointers on how to resolve. .

```
[2024-09-24 20:32:36,640] ERROR in app: Exception on /attach [POST]
Traceback (most recent call last):
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/metapyxl/c2pa-python-example/app.py", line 62, in resize
    builder.sign(signer, "image/jpeg", io.BytesIO(request_data), result)
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/c2pa/c2pa_api/c2pa_api.py", line 129, in sign
    return super().sign(signer, format, C2paStream(input), C2paStream(output))
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/c2pa/c2pa/c2pa.py", line 925, in sign
    rust_call_with_error(
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/c2pa/c2pa/c2pa.py", line 283, in rust_call_with_error
    uniffi_check_call_status(error_ffi_converter, call_status)
  File "/home/ubuntu/metapyxl/c2pa-python-example/c2pa-env/lib/python3.10/site-packages/c2pa/c2pa/c2pa.py", line 313, in uniffi_check_call_status
    raise error_ffi_converter.lift(call_status.error_buf)
c2pa.c2pa.c2pa.Error.Other: reason="bad parameter: Other ParamValidationError('Parameter validation failed:\\nInvalid length for parameter KeyId, value: 0, valid min length: 1')"
```

**Comment by shayan-NECX** [comment]
Never mind. The problem was that internally, in the python env, the openssl version was being fetched as 1.1.1 instead of v3. This first didnt let the following command run
```
openssl x509 -req \
-CA rootCA.crt \
-CAkey rootCA.key \
-in kms-signing.csr \
-out kms-signing.crt \
-days 365 \
-copy_extensions copyall
```
Ensuring that the certificates are created using OpenSSLv3, got everything to work. Also, i ran into an issue that AWS KMS doesnt show any SHA256 key generation option which the code relies on. The code doesnt accept KMS RSA keys, so using the code to generate both KMS key and CSR worked for me.
